baseURL = "https://jmf1sh.github.io/"

languageCode = "en-us"

title = "jonathan's blog"

theme = "kiera"
paginate = 10
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
canonifyurls = true

disqusShortname = "jmf1sh"
# googleAnalytics = ""

[author]
    name = "Jonathan Fisher"
    github = "jmf1sh"
    gitlab = "jmf1sh"
    linkedin = "jonathanfisher10"

[params]
    tagline = "mathematics, physics, programming, and machine learning"
    disableDarkModeCSS = true # disables css style for users using dark-mode

menu = "main"
meta = "false"




# uncomment to enable the Tags link on the main toolbar
[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1

# uncomment to enable the Categories link on the main toolbar
[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 1
