baseURL = "https://jmf1sh.github.io/"

languageCode = "en-us"

title = "jmf1sh's blog"

theme = "kiera"
paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
canonifyurls = true

disqusShortname = "jmf1sh"
# googleAnalytics = ""

[author]
    name = "Jonathan Fisher"
    github = "jmf1sh"
    gitlab = "jmf1sh"
    linkedin = "jonathanfisher10"

[params]
    tagline = "this is a pointless tagline"

menu = "main"
meta = "false"


